### ISSUE TITLE
Plot SkewT directly from WRF output file.

### ISSUE THREAD

**Issue by wxguy** [cwebster2/pyMeteo#6] opened 2015-12-23 22:00 UTC
Is it possible to include a feature to plot SkewT diagram directly from WRF output file? This can be something like provide lat, long and wrfout.nc to get SkewT plot.

If implemented, this would be a great feature.

**Comment by cwebster2** [comment] 2015-12-24 16:21
Great suggestion.  This should be straightforward to add. I'll work on it.

**Comment by wxguy** [comment] 2015-12-24 18:32
Thank you for acceptance. I am waiting for the new code.

One more suggestion. Your package is really good and one of the good looking SkewT diagram I found based on python. You can have some text/csv file with sounding data within your package and in the documentation page provide an example to plot SkewT diagram based on this sample file. This will greatly improve the visibility of your package. Also have some basic example on how to use this package from terminal for all the file format it is supported.

**Comment by cwebster2** [comment] 2015-12-28 17:02
This is now supported in the master branch.  Once I document it and the other skewT methods (issue #7) I'll bump the version number and push an image to pypi.  

There is now a command line script `skewt-wrf` that takes a wrfout netcdf file, lat, lon and time and will produce a skewT plot.  This calls `pymeteo.skewt.plot_wrf` and there is a new `pymeteo.wrf` module for some of the logic needed to handle the wrf output files.

**Comment by wxguy** [comment] 2015-12-28 17:08
Thanks for the code. Checking it right away.

**Comment by wxguy** [comment] 2015-12-28 17:27
Tested the code and it produces an Index Error. Terminal output is below:-
`wrfout_.nc` is the wrfout netCDF file
`13.08` is the lat
`80.27` is the long
`1` is the wrf time and 
`test` is the output file name

```
$ skewt-wrf -d wrfout_.nc 13.08 80.27 1 test
2015-10-13_00:00:00
Traceback (most recent call last):
  File "/usr/bin/skewt-wrf", line 27, in <module>
    skewt.plot_wrf(base,lat,lon,time,out)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 276, in plot_wrf
    print('LAT ',lat,': ',i, ': ',wrf_lats[j,i])
IndexError: index -758 is out of bounds for axis 1 with size 102
```

**Comment by cwebster2** [comment] 2015-12-28 17:45
Can you try

`skewt-wrf -d wrfout_.nc --lat 13.08 --lon 80.27 -t 1 -o test.pdf`

I'll get around to making these scripts print useful errors but wanted to get this out first.  The output file needs an extension (i think) as it determines the type of output to produce based on that.  If an error is still produced with the above command line, can you send me the wrfout_.nc file to take a look at it?

**Comment by wxguy** [comment] 2015-12-28 17:57
Here is what I received in the terminal:-

```
$ skewt-wrf -d wrfout_.nc --lat 14 --lon 80 -t 2 -o test.pdf
2015-10-13_02:00:00
Traceback (most recent call last):
  File "/usr/bin/skewt-wrf", line 27, in <module>
    skewt.plot_wrf(base,lat,lon,time,out)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 276, in plot_wrf
    print('LAT ',lat,': ',i, ': ',wrf_lats[j,i])
IndexError: index 149 is out of bounds for axis 0 with size 60
```

The file size is quite big (close to 800 - 850 Mb) and require some time to upload with my slow internet connection. Meanwhile, please provide the command/ script to test and I will get back with the terminal output.

**Comment by cwebster2** [comment] 2015-12-28 18:02
Could you run `ncdump -h wrfout_.nc` and post the output somewhere so I can look at it?  That might be all I need to save you from having to upload a large file.

**Comment by cwebster2** [comment] 2015-12-28 20:40
I'll add that this error is caused by the grid coordinates being out of bounds of the lat or long arrays (e.g. outside of the domain).  This can be a bug on my part in the ll_to_ij routine for your map projection or something else.

**Comment by wxguy** [comment] 2015-12-29 02:23
Well that was bad on my part to include Lat and Lon beyond the actual domain. But the result is same when I give the Lat and Lon with in the domain area. Here is the terminal output for new lat and lon:-

```
$ skewt-wrf -d wrfout_.nc --lat 9.6 --lon 76 -t 1 -o test.pdf
2015-10-13_01:00:00
Traceback (most recent call last):
  File "/usr/bin/skewt-wrf", line 27, in <module>
    skewt.plot_wrf(base,lat,lon,time,out)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 276, in plot_wrf
    print('LAT ',lat,': ',i, ': ',wrf_lats[j,i])
IndexError: index 102 is out of bounds for axis 0 with size 60
```

I have attached the ncdump log for your review.
[ncdump.txt](https://github.com/cwebster2/pyMeteo/files/73685/ncdump.txt)

Here is what I have done with one of the script I am developing for meteogram. I was able to extract temp for the same lat and lon:-

```
import numpy as np
from netCDF4 import Dataset

filename = 'wrfout_.nc'
nc = Dataset(filename)

# Set station Lat and Long
stn_lat = int(9.6)
stn_long = int(76)

# Get the forecasting time level of the wrfout file
total_time_interval = []
for time in range(0, len(nc.variables['T'])):
    total_time_interval.append(time)

# Get some required variables
sfctemp_C_list = []
sfctemp_unit = u"\u00B0" + "C"
sfcT = nc.variables['T2']
for time in total_time_interval:
    sfctemp_C = round(sfcT[time, stn_lat, stn_long] - 273)
    sfctemp_C_list.append(sfctemp_C)

print sfctemp_C_list
```

and it produced the temp list as output:-

```
[25.0, 25.0, 27.0, 28.0, 29.0, 31.0, 32.0, 32.0, 31.0, 32.0, 32.0, 31.0, 29.0, 27.0, 26.0, 25.0, 25.0, 25.0, 25.0, 24.0, 24.0, 24.0, 24.0, 24.0, 24.0, 24.0, 26.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 33.0, 33.0, 30.0, 29.0, 28.0, 27.0, 25.0, 24.0, 24.0, 24.0, 24.0, 24.0, 23.0, 23.0, 23.0, 23.0, 23.0, 25.0, 27.0, 29.0, 30.0, 31.0, 32.0, 33.0, 33.0, 31.0, 30.0, 30.0, 28.0, 28.0, 27.0, 26.0, 25.0, 25.0, 25.0, 25.0, 24.0, 24.0, 23.0, 23.0]
```

I could be wrong here and you can correct me on this.

**Comment by cwebster2** [comment] 2015-12-29 03:19
Thanks for the info.  I have one last (for now) request to aid my debugging.  Can you give me the values of the XLAT and XLONG arrays at index 0,0, e.g. `nc.variables['XLAT'][1,0,0]` and `nc.variables['XLONG'][1,0,0]`.  

My thoughts on your code above are that, as far as I understand it, the actual data, e.g. `T2` is indexed in i,j coordinates and if you are using lat,long you need to do a map transform to get the i,j coords.  In NCL, for example, if you give lat,long it ends up calling a Fortran routine DLLTOIJ to find indices for data access.  Unless you map projection happens to line up just right, you are accessing i,j=9,76 and not lat/long 9,76 in your code snippet (there will be data there but it won't be the right location).  

The wrfout file I had sitting around used a lambert map projection and that is what I tested against.  I'm debugging the mercator map projection (which is what your wrfout file uses) to make sure I translated it from the NCL Fortran routine properly.  I'll double-check it with the values I asked for above and I'll also give you a set of lat/lon that should work just to see what it outputs for you.  Thanks for helping me debug this!

**Comment by wxguy** [comment] 2015-12-29 13:11
Here is the modified code to include the line you requested.

```
import numpy as np
from netCDF4 import Dataset

filename = 'wrfout_.nc'
nc = Dataset(filename)
print nc.variables['XLAT'][1,0,0]
nc.variables['XLONG'][1,0,0]
```

I got the following output in terminal:-

```
6.94672
72.8312
```

Thanks for the detailed explanation. I was in doubt about my code (as I did get the values without an error :-)) ).

> Thanks for helping me debug this!

You are welcome. Finally it is going to help both python and scientific community as a whole.

**Comment by cwebster2** [comment] 2015-12-29 17:09
Thanks for the data.  I'm debugging the routine now but just to see what happens, can you run

`skewt-wrf -d wrfout_.nc --lat 5.0 --lon 76.0 -t 1 -o test.pdf`

Those coordinates are meaningless but with the current map transform will end up within the array bounds.  I'm interested to see the text output when you run that and whether or not it runs properly.  In the meantime I'm still looking into the map projection transform.

**Comment by wxguy** [comment] 2015-12-30 00:05
Little progress this time. Here is the output:-

```
$ skewt-wrf -d wrfout_.nc --lat 5.0 --lon 76.0 -t 1 -o test.pdf
2015-10-13_01:00:00
('LAT ', 5.0, ': ', 34, ': ', 11.953751)
('LON ', 76.0, ': ', 53, ': ', 76.088531)
(0, 0, 0.0, 1, 297.93509, -1.0416501, -0.25789595, 92401.016, 0.013785049)
Traceback (most recent call last):
  File "/usr/bin/skewt-wrf", line 27, in <module>
    skewt.plot_wrf(base,lat,lon,time,out)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 320, in plot_wrf
    plot(0. ,0. ,z, t, th, p, qv, u, v, filename, output)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 569, in plot
    plot_hodograph(ax2, z, u, v)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 701, in plot_hodograph
    ucb = dyn.storm_motion_bunkers(u,v,z)
  File "/usr/lib/python2.7/site-packages/pymeteo/dynamics.py", line 54, in storm_motion_bunkers
    u_0_500 = avg_wind(_u,_v,_z, 0., 500.)
  File "/usr/lib/python2.7/site-packages/pymeteo/dynamics.py", line 27, in avg_wind
    return (u/n, v/n)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by cwebster2** [comment] 2015-12-30 02:10
Thanks!

   Progress is progress!  From this I can see it is indeed the latitude that is not being transformed properly and now that I see how it is being transformed I have more to go on to fix it.   I also took care of gracefully handling that div by zero so that it doesn't kill the script, so that is progress as well.  I'll push a commit later tonight to hopefully address this all and I'll let you know when it is up.

**Comment by cwebster2** [comment] 2015-12-30 02:38
Found it!  A typo that I was missing all day where a `<` should have been a `!=`.  The fix is committed and pushed to the repo.  You can now use your actual coordinates:

`$ skewt-wrf -d wrfout_.nc --lat 9.6 --lon 76 -t 1 -o test.pdf`

that should decode the grid points (i,j) = (33,28).  If there are any problems with the plot, post the text output and the plot (or a link to it) and I'll work on it.   

Also, in your meteogram program, feel free to call `pymeteo.wrf.ll_to_ij` to do the coordinate transform.  Its not well documented yet, but in the next few days I'll be updating it with a version that you can just ass the NetCDF4 Dataset instead of manually passing values from it.

**Comment by wxguy** [comment] 2015-12-30 02:42
Just wait for a second. I am downloading it right now.

**Comment by wxguy** [comment] 2015-12-30 02:45
Struck at another problem. Here is the terminal output:-

```
$ skewt-wrf -d wrfout_.nc --lat 9.6 --lon 76 -t 1 -o test.pdf
2015-10-13_01:00:00
('lats/lons dims: ', (60, 102))
('LAT ', 9.6, ': ', 28, ': ', 9.6010742)
('LON ', 76.0, ': ', 33, ': ', 75.992729)
(0, 0, 0.0, 1, 301.15186, 0.27468511, -1.4772046, 101136.3, 0.018818898)
Traceback (most recent call last):
  File "/usr/bin/skewt-wrf", line 27, in <module>
    skewt.plot_wrf(base,lat,lon,time,out)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 320, in plot_wrf
    plot(0. ,0. ,z, t, th, p, qv, u, v, filename, output)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 573, in plot
    plt.savefig(output, dpi=300,bbox_inches=0)
  File "/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 688, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/figure.py", line 1539, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 196, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2230, in print_figure
    **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2536, in print_pdf
    self.figure.draw(renderer)
  File "/usr/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/figure.py", line 1133, in draw
    func(*args)
  File "/usr/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2304, in draw
    a.draw(renderer)
  File "/usr/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/text.py", line 796, in draw
    ismath=ismath, mtext=mtext)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2077, in draw_text
    return draw_text_simple()
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2006, in draw_text_simple
    self._setup_textpos(x, y, angle)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 1770, in _setup_textpos
    self.file.output(x - oldx, y - oldy, Op.textpos)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 589, in output
    self.write(fill([pdfRepr(x) for x in data]))
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 149, in pdfRepr
    raise ValueError("Can only output finite numbers in PDF")
ValueError: Can only output finite numbers in PDF
```

**Comment by cwebster2** [comment] 2015-12-30 02:51
well at least its a new issue  :)

I pushed another commit to master that will spit out some information on the arrays getting sent to the plotting routine.  Can you pull that and re-do the command above?  It'll still end up with the exception and stack trace, but I'll be able to see the data and figure out why that is happening (since I can't reproduce with my wrfout file).  Thanks for being patient.

**Comment by wxguy** [comment] 2015-12-30 02:57
Here is the debugging message:-

```
$ skewt-wrf -d ../old_wrf_plotting_scripts-master/wrfout_.nc --lat 9.6 --lon 76 -t 1 -o test.pdf
2015-10-13_01:00:00
('lats/lons dims: ', (60, 102))
('LAT ', 9.6, ': ', 28, ': ', 9.6010742)
('LON ', 76.0, ': ', 33, ': ', 75.992729)
(0, 0, 0.0, 1, 301.15186, 0.27468511, -1.4772046, 101136.3, 0.018818898)
[ 101136.3046875   100797.53125      99971.3984375    98852.7265625
   97445.40625      95696.921875     93512.765625     90892.9765625
   87042.9609375    82160.171875     77285.2421875    72418.78125
   65817.609375     57898.98046875   50776.41796875   44379.95703125
   38650.20703125   33528.41015625   28959.16796875   24892.08789062
   21281.29101562   18085.21289062   15265.07910156   12785.54492188
   10613.87304688    8720.015625      7076.27685547    5656.82861328]
[     0.             30.11538696    103.48806763    203.42379761
    330.5630188     490.24029541    693.01287842    941.31762695
   1318.57165527   1814.96191406   2335.54150391   2883.32788086
   3686.47680664   4731.38720703   5778.36328125   6828.95898438
   7882.62792969   8936.20800781   9988.45214844  11039.34277344
  12088.88476562  13136.5234375   14182.37109375  15231.70117188
  16300.1171875   17422.47265625  18644.11523438  19990.46679688]
[ 301.15185547  301.07305908  301.06292725  301.06689453  301.07958984
  301.44128418  302.18136597  303.00375366  304.48361206  306.68695068
  309.28460693  311.88391113  315.49234009  320.8661499   325.97399902
  331.90634155  336.73202515  340.33770752  343.7522583   346.53143311
  349.15374756  350.74981689  352.4848938   356.46813965  367.31921387
  392.98141479  431.60040283  469.5869751 ]
[ 0.27468511  0.2141853   0.22274287  0.23309466  0.23982641 -0.01485114
 -0.97769964 -2.35944128 -4.14654589 -5.00909996 -4.40022182 -2.62400174
 -0.22619     0.33385721 -1.4100827  -2.03568912 -2.70660758 -5.46401072
 -9.2687645  -8.66651917 -7.31954575 -6.34951162 -6.35857153 -8.59183216
 -8.30127144 -2.01154876  6.34280682  8.49809265]
[-1.47720456 -1.48186922 -1.46820331 -1.43099642 -1.36923695 -1.0809679
 -0.28034401  0.72824627  1.52775264  1.48237514  1.11611152  0.87334806
 -0.24181348 -1.43732142 -1.36976671 -1.13704371 -1.53739798 -1.06609881
 -0.69038689 -3.56384349 -3.63325047 -1.63354123  0.41438103 -0.34079829
 -1.45487368 -0.09732136  2.0640626   0.21578003]
[ 101136.3046875   100797.53125      99971.3984375    98852.7265625
   97445.40625      95696.921875     93512.765625     90892.9765625
   87042.9609375    82160.171875     77285.2421875    72418.78125
   65817.609375     57898.98046875   50776.41796875   44379.95703125
   38650.20703125   33528.41015625   28959.16796875   24892.08789062
   21281.29101562   18085.21289062   15265.07910156   12785.54492188
   10613.87304688    8720.015625      7076.27685547    5656.82861328]
[  1.88188981e-02   1.77619401e-02   1.75294727e-02   1.73988324e-02
   1.72312222e-02   1.64061189e-02   1.58520155e-02   1.56307649e-02
   1.46574536e-02   1.29882134e-02   1.11317541e-02   9.67478659e-03
   8.42783041e-03   6.21006219e-03   5.10617020e-03   3.67291085e-03
   2.33886018e-03   1.26966520e-03   6.03648543e-04   3.04679823e-04
   1.29808279e-04   4.62024655e-05   1.36182225e-05   4.43334011e-06
   2.71074146e-06   3.43757733e-06   1.51017355e-06   9.97768666e-07]
Traceback (most recent call last):
  File "/usr/bin/skewt-wrf", line 27, in <module>
    skewt.plot_wrf(base,lat,lon,time,out)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 327, in plot_wrf
    plot(0. ,0. ,z, t, th, p, qv, u, v, filename, output)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 580, in plot
    plt.savefig(output, dpi=300,bbox_inches=0)
  File "/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 688, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/figure.py", line 1539, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 196, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2230, in print_figure
    **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2536, in print_pdf
    self.figure.draw(renderer)
  File "/usr/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/figure.py", line 1133, in draw
    func(*args)
  File "/usr/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2304, in draw
    a.draw(renderer)
  File "/usr/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/matplotlib/text.py", line 796, in draw
    ismath=ismath, mtext=mtext)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2077, in draw_text
    return draw_text_simple()
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2006, in draw_text_simple
    self._setup_textpos(x, y, angle)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 1770, in _setup_textpos
    self.file.output(x - oldx, y - oldy, Op.textpos)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 589, in output
    self.write(fill([pdfRepr(x) for x in data]))
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 149, in pdfRepr
    raise ValueError("Can only output finite numbers in PDF")
ValueError: Can only output finite numbers in PDF

```

I actually tried to upload the wrfout file since yesterday (entire night) to mediafire. But at after 98 %  it popped up some error message. I will compress the wrfout package and upload it again today.

**Comment by cwebster2** [comment] 2015-12-30 03:00
While I mess around with this, try running this just to see if the issue is in the pdf backend:

`$ skewt-wrf -d wrfout_.nc --lat 9.6 --lon 76 -t 1 -o test.png`

**Comment by wxguy** [comment] 2015-12-30 03:11
Wow. It produces an image. Bad that I could not upload the image for your
review due to power supply failure. I will upload it after some time.

The image does not look same as seen on the documentation. Also it didn't
calculate the thermo dynamic parameters.

Could not resist replying. I am sending this message from my mobile :-))

**Comment by cwebster2** [comment] 2015-12-30 03:35
I'll get the diagnostic parameters back on the plots soon.  I did some refactoring of the skew-t code a little while back and that part of the plot is still a TODO, but I'll take care of it soon.  Glad to hear it produced some output.  I'll be looking at why the pdf didn't work and getting the diagnostic parameters sorted out.

**Comment by wxguy** [comment] 2015-12-30 04:03
Hope to see the new code soon.

**Comment by cwebster2** [comment] 2015-12-30 04:19
The data block (not in a finished state) is back and committed to master.  It is still a WIP and presentation will change a bit from its current state.

**Comment by cwebster2** [comment] 2015-12-30 19:51
I'm closing this issue since the basic problem is solved.  I've moved the issue with the pdf plot to a new issue #8 and will continue looking at it there.  If there is anything else wrong with plot output don't hesitate to open a new issue about it.

**Closed as completed by cwebster2** 2015-12-30 19:51 UTC
Labels: enhancement
